damdam6/일급객체와 javascript/일급객체와 javascript.md
1. 영어로 자료 검색해보고 원문 읽기(stack overflow랑 친해지기)
2. 한국어 블로그 글을 최대한 참고하지 않기(비판적 읽기)
3. js기본 원리 + 웹fe 기본 cs학습
4. 프로젝트 기반 용어 및 cs학습
* 일급 객체 정의
* 일급 객체와 일급함수의 차이
* 고차함수란?
* javascript의 함수 객체 기본
~**추가 학습 목표 사항**~
~랙시컬 스코프 개념~
~클로저 개념~
~클로저 활용 예시 및 장단점~
=> damdam6 - week01

dolmeengii /HTML meta 데이터의 종류와 사용방법/HTML meta 데이터의 종류와 사용방법.md
- HTML head 태그에서 사용되는 메타데이터의 종류
- 메타 데이터의 사용 예시 코드
💡 추후 공부해 볼 내용
- 프래그마 지시문에 대해
=> dolmeengii - week02

dolmeengii/HTML 메타 데이터의 종류와 사용방법/HTML 메타 데이터의 종류와 사용방법.md
HTML 메타데이터의 종류와 사용방법에 대해 알아보았습니다.
추후 비동기처리를 하며 async와 defer에 대해 알아보겠습니다.
=> dolmeengii - week02

gardener/js-this/README.md
1. This의 정의
2. This의 호출 - 함수/메소드로서 동작
=> gardener - week03

damdam6/콜백 함수/콜백함수.md
* 콜백 함수의 정의
* 콜백 함수 사용 이유
* 콜백 함수 사용 예시
=> damdam6 - week05

olrlozl/CORS/CORS.md
- Origin
- SOP
- CORS
- 동작 시나리오 3가지 
- CORS 에러 해결방법
=> olrlozl - week06

gardener/js-class/README.md
=> gardener - week07

olrlozl/MemoryLeak/MemoryLeak.md
- 메모리 누수란
- 메모리 누수가 발생할 수 있는 대표적 사례 4가지
- 불필요한 전역 변수 사용
- 분리된 노드 참조
- 해제하지 않은 타이머
- 잘못된 클로저 사용
메모리 누수와 사례에 대해서 간단하게 알아보았 습 니 ㄷr
=> olrlozl - week07

gardener/js-Exception/README.md
Exception
1) 구문 오류와 예외를 구분할 수 있다.
2) 기본 예외 처리와 고급 예외 처리를 이해한다.
3) 예외를 왜 발생시켜야하는지 이해한다.
4) 예외를 강제로 발생시키는 방법을 이해한다.
=> gardener - week08

damdam6/Reflow와 Repaint/Reflow와 Repaint.md
- repaint와 reflow 정의
-  최적화 방법
=> damdam6 - week09

bloblog/SOLID-js/SOLID-js.md
- 객체지향을 기반으로 하는 SOLID 원칙이 자바스크립트에서 어떻게 적용되는지 알아봄
=> bloblog - week12

bloblog/HTTP메서드와 멱등성/HTTP메서드와 멱등성.md
=> bloblog - week13

gardener/js-Express/README.md
1) Express 무엇인지 알아보기
2) React와 비교
3) 간단한 Express 예제 코드 알아보기
=> gardener - week13

gardener/js-Serveless/README.md
(week14) 서버리스 아키텍쳐
1) 서버리스 아키텍쳐
2) 서버리스 아키텍쳐의 필요성
3) 서버리스 아키텍쳐의 대표적인 도구
4) 서버리스 아키텍쳐의 구성 요소
=> gardener - week14

olrlozl/React-CustomHook/React-CustomHook.md
- 리액트 훅(Hook)이란
- 커스텀 훅(Custom Hook)이란
- 커스텀 훅(Custom Hook)의 사용 예시
- 커스텀 훅(Custom Hook)의 장점
=> olrlozl - week14

dolmeengii/JavaScript 복사와 전개연산자/JavaScript 복사와 전개연산자.md
이번 시간에는 JS 복사와 전개 연산자에 대해 알아보았습니다.
- JS의 복사 방식: 얕은 복사와 깊은 복사 개념과 사용 방법
- 전개 연산자의 개념과 사용 예시
---
항상 헷갈리는 복사에 대한 개념을 정리를 통해 다시 한 번 공부해보았습니다.
=> dolmeengii-week15

dolmeengii/Vanilla Extract CSS이란?/Vanilla Extract CSS이란?.md
이번 주차에는 예전에 진행했던 프로젝트에서 사용했던 스타일링 라이브러리 Vanilla Extract CSS에 대해 알아보았습니다.
- Vanilla Extract CSS의 개념
- Vanilla Extract CSS의 특징
- Vanilla Extract CSS 설치하기
---
다음 시간에는 추가적으로 다음의 내용을 알아보도록 하겠습니다.
=> dolmeengii-week16

dolmeengii/Vanilla Extract CSS : CSS 변수 사용/Vanilla Extract CSS : CSS 변수 정의 방식.md
이번주에는 Vanilla Extract CSS : CSS 변수 정의 방식에 대해 알아보았습니다.
- vars의 개념과 활용방안
- sprinkles의 개념과 활용방안
- vars와 sprinkles의 차이점
---
다음 시간에는 Vanilla Extract CSS : CSS 변수를 사용한 동적 스타일링에 대해 알아보겠습니다.
=> dolmeengii-week17

bloblog/코딩테스트대비/코딩테스트대비.md
- 반복문
- Array
- 문자열
- Map
한 번 정리해보면 좋을 것 같아 주제로 선정하였습니다!
=> bloblog - week17

olrlozl/zustand/zustand.md
- Zustand란
- Zustand 사용법
- Zustand 주요 장점
- Zustand가 Redux와 Context API 보다 나은 이유
- React 상태관리 라이브러리 비교 (Redux, Zustand, Jotai, Recoil)
=> olrlozl - week18

gardener/js-render/README.md
Browser, React, Next의 렌더링 과정
1) Browser의 렌더링 과정
2) React의 렌더링 과정
3) NextJS의 렌더링 과정
=> gardener - week18

gardener/TDD/README.md
feat(week18) TDD
1) Test Driven Development
2) Jest를 활용한 간단한 TDD
++ 다음 주에는 RTL, Cypress와 결합된 테스트 코드들에 대해서 알아본다.
=> gardener - week19

nijesmik/Feature-Sliced-Design/README.md
이번주는 FSD 구조에 대해 공부하였습니다.
- Concepts
- Define a strict public API
- Usage with NextJS
=> nijesmik - week19

olrlozl/TanstackQuery/TanstackQuery.md, olrlozl/TranstackQuery/TranstackQuery.md
Transtack Query (React Query)에 대해 알아보았습니다.
- 대표적인 기능
- useQuery
- useMutation
- QueryClient
=> olrlozl - week19

gardener/TDD/README2.md
feat(week20) TDD2
1) Jest + RTL을 결합한 컴포넌트 테스트
2) Jest + Cypress를 결합한 E2E 테스트
=> gardener - week20

olrlozl/React-CompoundComponent/React-CompoundComponent.md
[리엑트의 컴파운드 컴포넌트 패턴]
- 컴파운드 컴포넌트란?
- 유용한 경우
- 사용하는 이유
- 예제 코드: Accordion 컴포넌트
=> olrlozl - week20

nijesmik/TypeScript-satisfies/README.md
TypeScript의 `satisfies`에 대해 공부하였습니다.
=> nijesmik - week20

olrlozl/HttpOnlyCookie-JWT/HttpOnlyCookie-JWT.md
- JWT를 HttpOnly Cookie에 저장하는 이유
- JWT를 HttpOnly Cookie에 저장하는 방식
- XSS와 CSRF란
=> olrlozl - week22

gardener/js-project/DEPLOY.md
feat(week22) FE 플랫폼별 배포 전략
1) 각 플랫폼별 특징
2) 배포 플랫폼 개요
3) 배포 플랫폼별 비교
4) 배포 플랫폼별 비용 비교
=> gardener - week22

nijesmik/NextJS-cache/README.md
Next.js의
- 데이터 캐싱
- 캐싱된 데이터 업데이트
에 대해 공부하였습니다. 😄
=> nijesmik - week22

bloblog/next-server-actions/next-server-actions.md
- action 이란?
- next server actions 사용하기
Resolves: #119
=> bloblog - week23

gardener/Job-Interview/README.md, gardener/js-cdn/README.md
feat(week24) CDN
1) CDN 이전의 일반적인 네트워크 흐름
2) CDN
3) CDN의 적용
=> gardener - week24

dolmeengii/React Hooks/내장 Hooks 종류.md
React 내장 Hooks에 대해 간단히 알아보았습니다.
- React 내장 Hooks의 종류
- React 내장 Hooks의 개념과 사용방법
---
다음 시간에는 Custom Hook에 대해 알아보도록 하겠습니다.
=> dolmeengii - week25

bloblog/README.md, bloblog/server-component (2)/server-component-2.md
- Pages Router 와 App Router
- App Router 의 서버 컴포넌트
- 서버 컴포넌트에서 Context 사용하기
Resolve: #124
=> bloblog - week26
